# Generates shaders_registry.cpp from the headers sokol-shdc wrote.
#
# Usage: cmake -DOUT=<file> -DHEADERS=<a.glsl.h|b.glsl.h|...> -P GenShaderRegistry.cmake
#
# sokol-shdc's reflection helpers answer "what is the offset of uniform X in
# block Y", but offer no way to enumerate uniforms. The runtime needs the names
# (src/Engine/RL/rl_shader.cpp builds a by-name uniform table per program), so
# they are scraped here from the strcmp() chains inside those helpers. Each
# file's @module must equal its file stem; generated C symbols are
# <module>_<program>_*.

string(REPLACE "|" ";" HEADERS "${HEADERS}")

set(includes "")
set(tables "")
set(entries "")

foreach(header ${HEADERS})
    get_filename_component(fname "${header}" NAME)
    string(REGEX REPLACE "\\.glsl\\.h$" "" module "${fname}")
    string(APPEND includes "#include \"${fname}\"\n")

    # Only lines that define functions or compare names; none contain ';',
    # which would otherwise split a line into several CMake list items.
    file(STRINGS "${header}" lines REGEX "static inline|strcmp\\(")
    set(programs "")
    set(mode "")
    set(cur "")
    set(curUb "")
    foreach(line IN LISTS lines)
        if(line MATCHES "static inline const sg_shader_desc\\* ([A-Za-z0-9_]+)_shader_desc\\(")
            list(APPEND programs "${CMAKE_MATCH_1}")
            set(mode "")
        elseif(line MATCHES "static inline int ([A-Za-z0-9_]+)_uniform_offset\\(")
            set(mode "uniforms")
            set(cur "${CMAKE_MATCH_1}")
        elseif(line MATCHES "static inline int ([A-Za-z0-9_]+)_texture_slot\\(")
            set(mode "textures")
            set(cur "${CMAKE_MATCH_1}")
        elseif(line MATCHES "static inline int ([A-Za-z0-9_]+)_attr_slot\\(")
            set(mode "attrs")
            set(cur "${CMAKE_MATCH_1}")
        elseif(line MATCHES "static inline")
            set(mode "")
        elseif(mode STREQUAL "uniforms" AND line MATCHES "strcmp\\(ub_name, \"([A-Za-z0-9_]+)\"\\)")
            set(curUb "${CMAKE_MATCH_1}")
        elseif(mode STREQUAL "uniforms" AND line MATCHES "strcmp\\(u_name, \"([A-Za-z0-9_]+)\"\\)")
            string(APPEND u_${cur} "\"${curUb}\", \"${CMAKE_MATCH_1}\", ")
        elseif(mode STREQUAL "textures" AND line MATCHES "strcmp\\(tex_name, \"([A-Za-z0-9_]+)\"\\)")
            string(APPEND t_${cur} "\"${CMAKE_MATCH_1}\", ")
        elseif(mode STREQUAL "attrs" AND line MATCHES "strcmp\\(attr_name, \"([A-Za-z0-9_]+)\"\\)")
            string(APPEND a_${cur} "\"${CMAKE_MATCH_1}\", ")
        endif()
    endforeach()

    foreach(sym IN LISTS programs)
        string(LENGTH "${module}_" prefixLen)
        string(SUBSTRING "${sym}" ${prefixLen} -1 program)
        string(APPEND tables
            "static const char* const ${sym}_u[] = { ${u_${sym}}nullptr };\n"
            "static const char* const ${sym}_t[] = { ${t_${sym}}nullptr };\n"
            "static const char* const ${sym}_a[] = { ${a_${sym}}nullptr };\n")
        string(APPEND entries
            "    { \"${program}\", ${sym}_shader_desc, ${sym}_uniformblock_slot, ${sym}_uniformblock_size,\n"
            "      ${sym}_uniform_offset, ${sym}_uniform_desc, ${sym}_texture_slot, ${sym}_attr_slot,\n"
            "      ${sym}_u, ${sym}_t, ${sym}_a },\n")
    endforeach()
endforeach()

set(content "// Generated by cmake/GenShaderRegistry.cmake -- do not edit.
#include <cstring>
#include \"sokol_gfx.h\"
#include \"rl_programs.hpp\"

${includes}
namespace rli {
namespace {
${tables}
const ProgramInfo kPrograms[] = {
${entries}};
} // namespace

const ProgramInfo* FindProgram(const char* name) {
    for (const ProgramInfo& p : kPrograms) {
        if (std::strcmp(p.name, name) == 0) return &p;
    }
    return nullptr;
}
} // namespace rli
")

# Only touch the file when it changes, so dependents do not rebuild needlessly.
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
    if(old STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUT}" "${content}")
